### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by remojansen** [atrauzzi/protoculture#2]
Hi @atrauzzi thanks for sharing this project with me. I think you are doing a good job 👍 I'm not familiar with laravel but I understand your docs about ServiceProviders, Apps and Suites. I'm using a similar pattern for Rest Services but I'm curious about your usage of Redux. Could you please write a more realistic example? Something like a TODO app? I'm very curious to see how it works :) Thanks!

**Comment by atrauzzi** [comment]
Absolutely!  I've got a few other slightly-related things to prepare over the next bit (I'm presenting at a regional conference, will definitely be giving inversify a mention!), but I'll link to any finished ideas once they become available in this ticket.  

Thanks so much for taking the time to check this out at an early stage.

**Comment by remojansen** [comment]
No problem, thanks for helping me to spread the word about inversify :cupid: I will review the app / slides once you share them here :+1:

**Comment by atrauzzi** [comment]
With that DI issue fixed, here's a demo app that should work if you want to try it out: https://github.com/atrauzzi/protoculture/blob/master/demo/console.ts

Starts to give a general feel of how apps would be composed.  More to come.

**Comment by atrauzzi** [comment]
@remojansen - A very early example of how some of the classes look in use: https://github.com/atrauzzi/azure-bootcamp-2017

Will be presenting with this project on Saturday.  I put this together in a pinch, so the project structure isn't finalized and obviously there's reams of shear layers to be made for the various libraries and lifecycles going on.

But it'll do well for a demo. ;)

**Comment by remojansen** [comment]
Hi @atrauzzi thanks a lot for the example, this example helps me a lot to understand your framework. 

I like it I think it helps to create self-contained services that don't need to be aware of each other. This architecture should be quite scalable. 

My recommendation at this point is to ensure that you have very good documentation and learning resources, also try to post online about it so people starts playing with it and gaining adoption. 

You have something that works, now you need to make working with that something as easy and enjoyable as possible for the developers.

If you keep working on it adding new features, improving performance, devtools... (even if nearly no one is using it) after some time it will pay off.

For example, it took over a year of adoption of inversify start happening:

![selection_032](https://cloud.githubusercontent.com/assets/10656223/25120242/33693c46-2415-11e7-8232-e6121ba01eae.png)

**Comment by atrauzzi** [comment]
@remojansen - Added the beginnings of a hapi integration today: https://github.com/atrauzzi/protoculture-hapi

Going to get it building on travis which should have it pushing as a package to npm shortly.

I love that graph, something encouraging about it.  Even if only I use this library for the longest time, it's nice to see that so long as it's useful, there's always a chance for interest to pick up!

One day I'll close this issue -- but not yet :)

**Comment by remojansen** [comment]
Hi, I just took a look to the hapi example and I liked it. I don't know if you agree but I would prefer the routing to be declarative. Something like:

```ts
#!/usr/bin/env ts-node
import { ServiceProvider, StaticServiceProvider, BaseApp, Suite, ConsoleServiceProvider } from "protoculture";
import { HapiServiceProvider, Route } from "../src/index";
import * as Hapi from "hapi";


const hapiDemoSymbols = {
    HelloController: Symbol("hello"),
}

export class HelloController {
    
    // Controllers can be async now!
    @action("GET", "/") // add config as decorators
    public async sayHello(request: Hapi.Request, reply: Hapi.IReply, route: Route) {

        reply("Hello!");
    }
}

class HapiDemoServiceProvider extends HapiServiceProvider {

    public async boot() {

        this.bindConnection({
            host: "0.0.0.0",
            port: 2112,
        });

        this.bindConstructor(hapiDemoSymbols.HelloController, HelloController);

        // use metadata to register routes and makes controller an injectable
        this.registerController(HelloController); 

        super.boot();
    }
}

//
// Here's a suite that acts as the composition root for the entire solution.
class HapiDemoSuite extends Suite {

    public name = "hapi-demo";

    protected get serviceProviders(): StaticServiceProvider<any>[] {

        return [
            HapiDemoServiceProvider,
            ConsoleServiceProvider,
        ];
    }
}

//
// And this is how we start it!
const suite = new HapiDemoSuite();
suite.run().catch(console.error);
```

I have a talk about InversifyJS soon I will mention that you are working on this.

**Comment by atrauzzi** [comment]
Oh yeah, that would be neat! I could probably quite easily create an annotation reader that gets called in the service provider.

It would probably also need injectable at that point. But boundaries are usually the one place where I don't mind having shortcuts like annotations.

Consider it added to my pipeline!

**Comment by atrauzzi** [comment]
Going to circle back and make the route annotations shortly.  In the meantime however, I wanted to get a start-to-finish scenario going in preparation for my presentation next month.

A little work to be done, but it's finally at a workable state: https://github.com/atrauzzi/protoculture-react

React! :)

**Comment by atrauzzi** [comment]
Finally had a bit of time yesterday evening to to make progress on my `ServiceProvider` developer-joy concerns.  All thanks to my bumbling around here: https://github.com/Microsoft/TypeScript/issues/15818

Which has resulted in:
https://github.com/atrauzzi/protoculture-hapi/blob/master/src/Extensions.ts#L19-L50

Moving forward again, also have started engaging with the [new glimpse nodejs package](http://node.getglimpse.com) to see if it has a place to fit with the hapi integration!

**Comment by remojansen** [comment]
Nice!, I'm going to try http://node.getglimpse.com/ looks neat:)

**Comment by atrauzzi** [comment]
Haha, woops, messed up that link ;)

Yeah, I should be able to get it in as a service provider.  It's a bit aggressive on its requirements, needing to be started before other modules are imported.

Also started this now that I have enough bits to make projects: http://github.com/atrauzzi/protoculture-evolution-chamber

If you have the time (I barely do!), comments always welcome on that structure.  Still working out the details and making adjustments as necessitated.

**Comment by atrauzzi** [comment]
@remojansen - Nice milestone this morning:

https://github.com/atrauzzi/protoculture-hapi/blob/master/demo/server.ts#L15-L23

I've got controller annotations working!  As always, I'm interested in your thoughts on how I structured things:

 - https://github.com/atrauzzi/protoculture-hapi/blob/master/src/Decorator/Action.ts
 - https://github.com/atrauzzi/protoculture-hapi/blob/master/src/HapiServiceProvider.ts#L96-L102
